export enum Actions {
  FETCH_LUAS_STOPS_INIT = 'FETCH_LUAS_STOPS_INIT',
  FETCH_LUAS_STOPS_SUCCESS = 'FETCH_LUAS_STOPS_SUCCESS',
  FETCH_LUAS_STOPS_ERROR = 'FETCH_LUAS_STOPS_ERROR',
  FETCH_LUAS_STOP_TIMES_INIT = 'FETCH_LUAS_STOP_TIMES_INIT',
  FETCH_LUAS_STOP_TIMES_SUCCESS = 'FETCH_LUAS_STOP_TIMES_SUCCESS',
  FETCH_LUAS_STOP_TIMES_ERROR = 'FETCH_LUAS_STOP_TIMES_ERROR',
  SET_NEAREST_LUAS_STATION = 'SET_NEAREST_LUAS_STATION',
};
